version: 0.2

phases:
  install:
    commands:
      - echo Installing Serverless...
      - npm install -g serverless

  pre_build:
    commands:
      - echo Installing source npm packages
      - npm install
      - echo Trying to see if we can talk to AWS
      - curl -s "http://nib-kaos-secure-nib-aws-map-ap-southeast-2.s3-website-ap-southeast-2.amazonaws.com/master/ap-southeast-2/kaos/secure/deployer_role_arn"

  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with Serverless framework
      - sls deploy -v -s $ENV_NAME

  post_build:
    commands:
      - echo Deployment completed on `date`l
